sudo: required
services:
  - docker

before_install:
  - docker build -t chiragdeshmukh/docker-react -f Dockerfile.dev .

script:
  - docker run chiragdeshmukh/docker-react npm run test -- --coverage
